### ISSUE TITLE
编译不过：Plugin [id: 'org.jetbrains.kotlin.jvm', version: '1.3.41'] was not found in any of the following sources

### ISSUE THREAD

**Issue by ckrgithub** [PureWriter/desktop#2]
Plugin [id: 'org.jetbrains.kotlin.jvm', version: '1.3.41'] was not found in any of the following sources:

- Gradle Core Plugins (plugin is not in 'org.gradle' namespace)
- Plugin Repositories (could not resolve plugin artifact 'org.jetbrains.kotlin.jvm:org.jetbrains.kotlin.jvm.gradle.plugin:1.3.41')
  Searched in the following repositories:
    Gradle Central Plugin Repository

**Comment by zwt-ss** [comment]
hello！我在今晚也尝试进行了构建，并且遇到了相同的错误。
这个错误似乎是国内的网络环境引发的，gradle或maven无法下载到需要的文件。
错误报告显示maven无法从[这里](https://repo.maven.apache.org/maven2/org/jetbrains/kotlin/kotlin-compiler-embeddable/1.3.41/kotlin-compiler-embeddable-1.3.41.jar)下载到kotlin-compiler-embeddable-1.3.41.jar，在我的网络下直接用下载工具下载该文件需要40分钟左右。
总之我在执行以下操作后这个错误消失了：
1.为maven配置阿里云镜像。
2.多次重试build，在等待40+min后构建成功了。（这个时间格外漫长，虽然实际上这个文件仅有35265kb……推测应该大部分用在了龟速下完这个文件上。）
以上，希望能帮到你。
：）

**Comment by ckrgithub** [comment]
谢谢
