### ISSUE TITLE
夜间模式右键菜单未适配

### ISSUE THREAD

**Issue by chr233** [PureWriter/desktop#26]
![image.png](https://i.loli.net/2020/09/07/MVsK7Ui4kQdF1gG.png)

字体变成白色了，菜单背景没有变

**Comment by drakeet** [comment]
感谢反馈，很快将修复

Thanks,
Drakeet Xu

________________________________

**Comment by drakeet** [comment]
v0.3.1 已修复，再次感谢！
![image](https://user-images.githubusercontent.com/5214214/92390273-20020300-f14d-11ea-899d-af130eaa031c.png)
