### ISSUE TITLE
可否适配m1芯片？

### ISSUE THREAD

**Issue by Yeba** [PureWriter/desktop#30]
虽然也能运行，但是还想希望能直接跑原生架构。
感觉会快一点？（精神洁癖）
不知道是否有技术难度，如果很难就算了
目前vscode写md感觉良好😂

**Comment by LiarOnce** [comment]
自己编译的话应该是没有问题的，没什么难度，但是这个桌面版可能要大改

**Comment by yw662** [comment]
我提取了.deb版本的jar文件，然后在m1下用m1的jre运行，结果是可以运行的，但我能确定的也就仅限于可以运行，没有做进一步的测试。
我看了.deb包的全部文件，像这样直接运行“应该”是没有问题的，只需要把它进一步封装成.app就可以了。

如果 @drakeet 同意的话，我可以提供具体细节，以及帮忙研究一下要怎么封装成.app，这样x86的版本应该也可以做到不需要那个.pkg安装器。

**Comment by drakeet** [comment]
@yw662  我们知道如何打包出 M1 版，但由于当前 macOS 版完全能够在 M1 上允许，并且性能极佳，我试过专门的 M1 版，性能没有差别，所以本着能省则省的原则，不提供 M1 版。

**Comment by drakeet** [comment]
顺便说一下，我们的 JRE 是特制且修改过许多 JDK 源码的自编译版本，如果使用别的任何 JDK 都会导致一些问题，比如会遇到无法输入中文引号等问题。
