### ISSUE TITLE
可否支持安装目录自主选择

### ISSUE THREAD

**Issue by losic719** [PureWriter/desktop#35]
win10
就是安装的时候直接就安装了，没法选择安装目录

**Comment by drakeet** [comment]
为了避免中文路径导致无法使用
________________________________
From: losic719 ***@***.***>
Sent: Thursday, April 15, 2021 8:17:04 PM
To: PureWriter/desktop ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [PureWriter/desktop] 可否支持安装目录自主选择 (#35)


win10
就是安装的时候直接就安装了，没法选择安装目录

―

**Comment by losic719** [comment]
那，请问一下，这个会像之前那个版本一样会提供.7z和.zip的便携式的安装包吗

**Comment by drakeet** [comment]
不会。也是为了避免用户将文件放置在带有中文路径的目录。
