### ISSUE TITLE
Windows下图标锯齿很严重

### ISSUE THREAD

**Issue by Youxikong** [PureWriter/desktop#36]
![图片](https://user-images.githubusercontent.com/26603498/115096910-e5214280-9f59-11eb-897d-08eb5afdfe3c.png)
如图，图标锯齿非常严重。

**Comment by losic719** [comment]
![image](https://user-images.githubusercontent.com/45068706/115100161-91205900-9f6d-11eb-87ac-0c77ce5e6713.png)
我的这里还行哎，你是有放大吗

**Comment by Youxikong** [comment]
> ![image](https://user-images.githubusercontent.com/45068706/115100161-91205900-9f6d-11eb-87ac-0c77ce5e6713.png)
> 我的这里还行哎，你是有放大吗

100%显示，没有放大的。

**Comment by Carlos920** [comment]
![image](https://user-images.githubusercontent.com/32257015/115108386-c6936980-9fa2-11eb-9b19-701fa41e5f29.png)
我这也是图标锯齿严重

**Comment by sooxin** [comment]
> ![图片](https://user-images.githubusercontent.com/26603498/115096910-e5214280-9f59-11eb-897d-08eb5afdfe3c.png)
> 如图，图标锯齿非常严重。

和你一样锯齿严重，不知道是不是 2K 屏的缘故

**Comment by Youxikong** [comment]
原来Ctrl+滚轮可以放大缩小桌面的吗？学到了。
