### ISSUE TITLE
enhancement: 鼠标右键弹出的菜单文字没有本地化

### ISSUE THREAD

**Issue by sooxin** [PureWriter/desktop#42]
在 设置 --> 语言 选项里选择了“自动跟随系统”或者是中文（简体或繁体）选项，编辑器里的右键菜单仍然显示为英文。

如图：

![image](https://user-images.githubusercontent.com/16705366/118404976-d8eaeb00-b6a7-11eb-8dfc-520499eea213.png)

可以的话，希望能够把右键菜单的文本也本地化一下。😁

**Comment by drakeet** [comment]
感谢反馈！下一版解决。

Thanks,
Drakeet Xu
________________________________
From: Sooxin ***@***.***>
Sent: Monday, May 17, 2021 12:41:06 AM
To: PureWriter/desktop ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [PureWriter/desktop] enhancement: 鼠标右键弹出的菜单文字没有本地化 (#42)


在 设置 --> 语言 选项里选择了“自动跟随系统”或者是中文（简体或繁体）选项，编辑器里的右键菜单仍然显示为英文。

如图：

[image]<https://user-images.githubusercontent.com/16705366/118404976-d8eaeb00-b6a7-11eb-8dfc-520499eea213.png>

可以的话，希望能够把右键菜单的文本也本地化一下。😁

**Comment by drakeet** [comment]
下一版已解决。
