### ISSUE TITLE
桌面数据丢失

### ISSUE THREAD

**Issue by f15534666671** [PureWriter/desktop#6]
在PC端输入时，与Android端连接有时会丢失，但是Android端和PC端还是有很长一段时间显示已连接，导致PC端输入的大量内容由于没有备份在突然断开时无法保存也无法找回。（第一次写的时候丢东西，不得不从头来一次😭）

希望能从PC端引入备份。

**Comment by drakeet** [comment]
抱歉和感谢反馈，近期将规避这个情况。

**Comment by drakeet** [comment]
已经在 0.1.7 中解决，待发布更新。
