### ISSUE TITLE
PureWriter 1.5.3 - 對應移動端20.2.8 無法完成局域網連線

### ISSUE THREAD

**Issue by ygyuuffut** [PureWriter/desktop#63]
### 條件：
在MacOS 12.4 （Apple M series CPU）上面的桌面版無法正常連線移動版20.2.8 （Samsung SM T860 Android 12）,共用5Ghz無線網路且IP地址前三節均一致

### 觀察到的現象：
雖然移動端已經打開連線模式且軟體已經開始顯示IP地址（只有一個IP）但當相同IP被輸入至電腦端的時候沒有產生任何反應

### 已經嘗試的解決方法:
重新啟動任意一側的軟體並沒有成功修復問題
已經檢查無線網路設定並且沒有發現局域網連線被封鎖
重新安裝軟體並沒有解決問題

### 有效但是很燒錢的方法 (更新1)：
使用手機作為無線基站然後將兩個設備同時置於該網絡

### 額外的信息：
在接受來自Google PlayStore於七月六日推送的20.2.8公開更新之前沒有此連線問題
在切換網路之後似乎可以解決這個問題，該現象的重複性目前未知，並且無法確認其以後不會發生（更新1）

_十分感謝您的協助_

**Comment by drakeet** [comment]
您好，这是您的局域网可能存在内网隔离导致的，请试试手机开热点给电脑使用，再连接桌面版。手机和电脑都不要开 VPN。我这边测试没有问题，最近也没有修改过相关内容：
![image](https://user-images.githubusercontent.com/5214214/178130389-87a47f05-f45b-42aa-9c48-0848415fa1c2.png)

**Comment by ygyuuffut** [comment]
> 您好，这是您的局域网可能存在内网隔离导致的，请试试手机开热点给电脑使用，再连接桌面版。手机和电脑都不要开 VPN。我这边测试没有问题，最近也没有修改过相关内容： ![image](https://user-images.githubusercontent.com/5214214/178130389-87a47f05-f45b-42aa-9c48-0848415fa1c2.png)

關於內網的設定已經檢查，並未發現任何內網隔離或可能造成該現象的設定被打開。
會在未來的時日注意虛擬網絡代理的使用，十分感謝您的的軟體以及問題協助
若該問題在上述修正啟用後仍舊持續或升級將會再次聯絡。
