### ISSUE TITLE
24年3月了，当初的饼还在吗？

### ISSUE THREAD

**Issue by little3tar** [PureWriter/desktop#80]
希望可以给一个大概的时间，或者这个桌面版的项目是否还在······😎

**Comment by zydchina818** [comment]
24年4月了，桌面版还不能更新一下吗？

**Comment by ww201** [comment]
你不会是要跑路了吧

**Comment by walkdy2019** [comment]
2024年4月咯

**Comment by shen-li-ling-hua** [comment]
公众号给了个时间, 大概在六月底左右. 

> 本文由 [简悦 SimpRead](http://ksria.com/simpread/) 转码， 原文地址 [mp.weixin.qq.com](https://mp.weixin.qq.com/s?__biz=MzU2NTc0NTIxNg==&mid=2247484661&idx=1&sn=389703f737ba0abfd2d38abe8feb7fc7&chksm=fcb647dacbc1cecc42b004437d94a7274ffe4cf1f90ca19a4976b98a293cc3e802d2a81bf5e1&mpshare=1&scene=1&srcid=0608BOM5Gy73k88clGNkxKYy&sharer_shareinfo=6de5a25b2b4b1e2509c46c24763c5742&sharer_shareinfo_first=6de5a25b2b4b1e2509c46c24763c5742#rd) 纯纯写作@Drakeets 2024-04-12 16:34

亲爱的用户朋友们，  

近来我们收到一些信件询问纯纯写作最近很久没有大更新了，怎么回事？今天特别说明一下：

最近我们的主程在工作和生活方面发生了一些变动，因此每天所能用于工作的时间有所减少，但不用担心，四月**已经恢复正常了**，我们正在全力准备在春季结束之前（大概 6 月 21 日之前）发布新的桌面版，这是一项巨大的五年工程，所以并不是一时能完成的，麻烦大家再等等。  

Android 版目前更新有所暂缓，一来是因为**它已经非常成熟**了，经过曾经非常疯狂的开发和更新，最新版本号已经达到 v25.2.10 了，其实不太需要再高频更新了。

此外，经常有用户来信误解我们版本号提升太快说我们在「刷版本号」，对此今天顺便做一下解释：

纯纯写作的许多更新在一些用户看来可能“无关紧要”，但对于许多用户又是很重要的，润物细无声。我们是独立开发小团队，人手时间精力都非常有限，所以请相信我们，如果不是重要的更新，我们肯定不会付出精力去开发和更新的，所以不存在「刷版本号」的意图，所有更新都是实打实对用户有帮助的内容，可能您察觉不到，但纯纯写作就是这样，蕴繁于简，润物细无声，如果您感觉到版本号更新得很快，应该是因为我们非常投入在开发，热爱且疯狂地改善和打磨它，夜以继日，于是版本有时更新比较频繁，并非在刷版本号，这对我们没有益处。希望顺便能在这个问题上获得一些理解。

总的来说，我们将竭尽全力完成新桌面版的开发和发布，请多给我们一些耐心和理解，在这段时间期间，**我们暂时不会查看微信公众号上的任何消息（微信公众号不是我们的正常反馈渠道）**，如果您有什么紧急或重要的消息，请通过**邮箱联系**我们，感谢您的配合：

drakeet@drakeet.com

**Comment by shen-li-ling-hua** [comment]
> 可是现在已经快七月底了

![image](https://github.com/user-attachments/assets/725ba35d-e1c8-4fd4-9725-ea3362c8d34d)
公众号是这么说. 先等着吧
